# Generated by Django 5.2 on 2025-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
