# Generated by Django 5.2 on 2025-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_tag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
